In [18]:
import torch

In [19]:
dispositivo = torch.device("cuda" if torch.cuda.is_available() else "cpu")

In [20]:
# tensor de 3 uns
a = torch.ones(3).to(dispositivo)
a

tensor([1., 1., 1.], device='cuda:0')

In [21]:
# criando tensor com zeros e atribuindo valores
# tensores são alocaods na memória sequencialmente
# diferentemente de listas e tuplas em python que são alocadas de forma esparsa
# tensores são alocados de forma densa
# tensores são alocados de forma sequencial
pontos = torch.zeros(6).to(dispositivo)
pontos[0] = 4.0
pontos[1] = 1.0
pontos[2] = 5.0
pontos[3] = 3.0
pontos[4] = 2.0
pontos[5] = 1.0
pontos

tensor([4., 1., 5., 3., 2., 1.], device='cuda:0')

In [22]:
# criando tensor passando uma lista
pontos1 = torch.tensor([4.0, 1.0, 5.0, 3.0, 2.0, 1.0]).to(dispositivo)
pontos1

tensor([4., 1., 5., 3., 2., 1.], device='cuda:0')

In [23]:
# criando um tensor bidimensional
bidimensional = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]]).to(dispositivo)
print(bidimensional, bidimensional.shape)

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]], device='cuda:0') torch.Size([3, 2])


In [24]:
# acessando elementos do tensor
# acessando o elemento da primeira linha e segunda coluna
print(bidimensional[0, 1])

tensor(1., device='cuda:0')


In [25]:
# simulando o shape de uma imagem
# 3 canais, 256 linhas e 256 colunas

imagem = torch.randn(3, 5, 5).to(dispositivo) # [canal, linha, coluna]
pesos = torch.tensor([0.2126, 0.7152, 0.0722]).to(dispositivo)

# adicionando uma dimensão ao tensor
batch_t = torch.rand(2, 3, 5, 5).to(dispositivo) # [batch, canal, linha, coluna]

print(imagem.shape, pesos.shape, batch_t.shape)

torch.Size([3, 5, 5]) torch.Size([3]) torch.Size([2, 3, 5, 5])


In [26]:
# A vezes, os canais RGB estão na dimensão 0, e às vezes estão na dimensão 1.
# Mas podemos generalizar contando a partir do final: 
# eles estão sempre na dimensão –3, o terceiro a partir do final.

imagem_cinza = imagem.mean(-3) # média dos canais
print(imagem_cinza.shape)

torch.Size([5, 5])


In [27]:
batch_t_cinza = batch_t.mean(-3)
print(batch_t_cinza.shape)

torch.Size([2, 5, 5])


In [28]:
pesos_nao_apertados = pesos.unsqueeze(-1).unsqueeze_(-1)
imagem_pesos = (imagem * pesos_nao_apertados)

print(imagem_pesos.shape, pesos_nao_apertados.shape)

torch.Size([3, 5, 5]) torch.Size([3, 1, 1])


In [29]:
batch_t_pesos = (batch_t * pesos_nao_apertados)
print(batch_t_pesos.shape)

torch.Size([2, 3, 5, 5])


In [30]:
imagem_cinza_com_pesos = imagem_pesos.sum(-3)
print(imagem_cinza_com_pesos.shape)

torch.Size([5, 5])


In [31]:
batch_t_cinza_com_pesos = batch_t_pesos.sum(-3)
print(batch_t_cinza_com_pesos.shape)

torch.Size([2, 5, 5])


In [32]:
a = torch.tensor(range(9))
a

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [33]:
b = a.view(3, 3)
b

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [34]:
c = b[1:, 1:]
c

tensor([[4, 5],
        [7, 8]])